FROM qiime2/core:2019.1
MAINTAINER Mingxun Wang "mwang87@gmail.com"

RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential

RUN apt-get install -y unzip
#RUN wget https://github.com/mwang87/q2_metabolomics/archive/2.zip && unzip 2.zip && cd q2_metabolomics-2 && pip install .
RUN pip install tensorflow
RUN pip install tqdm

RUN pip install git+https://github.com/biocore/rhapsody.git
#RUN pip install git+https://github.com/biocore/rhapsody.git@q2-quick-fix
RUN qiime dev refresh-cache

COPY . /app
WORKDIR /app
